SUPABASE_URL = "https://qipphcdzlmqidhrjnjtt.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1Ni`IsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpcHBoY2R6bG1xaWRocmpuanR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY5NTIwMTIsImV4cCI6MjA4MjUyODAxMn0.AsuvjVGCLUJF_IPvQevYASaM6uRF2C6F-CjwC3eCNVk"
GEMINI_API_KEY = "AIzaSyAQaiwm46yOITEttdr0ify7duXCW3TwGRo"